### ISSUE TITLE
Android 13 API 33

### ISSUE THREAD

**Issue by epetre** [thomas550i/cordova-plugin-doze-Optimize#13]
This plugin doesn't seem to work on API 33.
After a basic install, it isn't available in the cordova plugins when using Android 13 and API 33 on a real device.

`cordova.plugins.DozeOptimize...`

**Comment by thomas550i** [comment]
any contributors ?

**Comment by epetre** [comment]
Terribly sorry, it actually works. It turns out it was a problem on my end.
