### ISSUE TITLE
RequestOptimizations does not wait for intent to finish

### ISSUE THREAD

**Issue by abroekhuis** [thomas550i/cordova-plugin-doze-Optimize#3]
The code that is used to request the whitelisting does not wait for the intent to finish. This results in unwanted behaviour where the actual application already continues with the next steps, while the popup is shown.
Even worse in this case, if the user does not allow the whitelisting, there is no way to know this as part of the call. It could be requested again using the provided API, but that does make usage of this plugin strange/difficult.

**Comment by wildhart** [comment]
I agree, the behaviour of this plugin is unexpected as described above.

**Comment by angel1st** [comment]
@abroekhuis, @wildhart  - since this plugin doesn't do what it claims in the right way, did you find an alternative one which can be used for the purpose? I am facing a similar issue and I have to allow my users to turn off doze mode in the app and WAIT until user returns their answer, then to proceed according to it.

**Comment by abroekhuis** [comment]
I have not found a reliable way to do this. The Android intent for this action doesn't provide a callback or something similar. At the moment I am not in need of something, so I have not created something myself.
I think some kind of polling is needed, if you want to be sure it is enabled. Looking at the app "MyTrails", they solved it by asking the user to disable power saving for it, if this is not done, the app simply continues. The next time a track is started, the user is asked again. There is also an option in there to never ask again.
With the current Android API, I think that is the most clean solution that is easily done.
